// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {git} from '../models';
import {main} from '../models';
import {prompt} from '../models';
import {config} from '../models';
import {skill} from '../models';
import {install} from '../models';
import {backup} from '../models';

export function AddCustomTool(arg1:string,arg2:string):Promise<void>;

export function AddStarredRepo(arg1:string):Promise<git.StarredRepo>;

export function AddStarredRepoWithCredentials(arg1:string,arg2:string,arg3:string):Promise<git.StarredRepo>;

export function ApplyAppUpdate():Promise<void>;

export function BackupNow():Promise<void>;

export function CheckAppUpdate():Promise<main.AppUpdateInfo>;

export function CheckAppUpdateAndNotify():Promise<main.AppUpdateInfo>;

export function CheckMissingPushDirs(arg1:Array<string>):Promise<Array<Record<string, string>>>;

export function CheckUpdates():Promise<void>;

export function CreateCategory(arg1:string):Promise<void>;

export function CreatePrompt(arg1:string,arg2:string,arg3:string,arg4:string):Promise<prompt.Prompt>;

export function CreatePromptCategory(arg1:string):Promise<void>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeletePrompt(arg1:string):Promise<void>;

export function DeletePromptCategory(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DeleteSkills(arg1:Array<string>):Promise<void>;

export function DeleteToolSkill(arg1:string,arg2:string):Promise<void>;

export function DownloadAppUpdate(arg1:string):Promise<void>;

export function ExportPrompts():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<config.AppConfig>;

export function GetEnabledTools():Promise<Array<config.ToolConfig>>;

export function GetGitConflictPending():Promise<boolean>;

export function GetLogDir():Promise<string>;

export function GetSkillMeta(arg1:string):Promise<skill.SkillMeta>;

export function GetSkillMetaByPath(arg1:string):Promise<skill.SkillMeta>;

export function GetSkippedUpdateVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportLocal(arg1:string,arg2:string):Promise<skill.Skill>;

export function ImportPrompts():Promise<number>;

export function ImportStarSkills(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function InstallFromGitHub(arg1:string,arg2:Array<install.SkillCandidate>,arg3:string):Promise<void>;

export function ListAllStarSkills():Promise<Array<git.StarSkill>>;

export function ListCategories():Promise<Array<string>>;

export function ListCloudFiles():Promise<Array<backup.RemoteFile>>;

export function ListCloudProviders():Promise<Array<Record<string, any>>>;

export function ListPromptCategories():Promise<Array<string>>;

export function ListPrompts():Promise<Array<prompt.Prompt>>;

export function ListRepoStarSkills(arg1:string):Promise<Array<git.StarSkill>>;

export function ListSkills():Promise<Array<main.InstalledSkillEntry>>;

export function ListStarredRepos():Promise<Array<git.StarredRepo>>;

export function ListToolSkills(arg1:string):Promise<Array<main.ToolSkillEntry>>;

export function MovePromptCategory(arg1:string,arg2:string):Promise<void>;

export function MoveSkillCategory(arg1:string,arg2:string):Promise<void>;

export function OpenFolderDialog(arg1:string):Promise<string>;

export function OpenLogDir():Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PromptRootDir():Promise<string>;

export function PullFromTool(arg1:string,arg2:Array<string>,arg3:string):Promise<Array<string>>;

export function PullFromToolForce(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function PushStarSkillsToTools(arg1:Array<string>,arg2:Array<string>):Promise<Array<main.PushConflict>>;

export function PushStarSkillsToToolsForce(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function PushToTools(arg1:Array<string>,arg2:Array<string>):Promise<Array<main.PushConflict>>;

export function PushToToolsForce(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function ReadSkillFileContent(arg1:string):Promise<string>;

export function RemoveCustomTool(arg1:string):Promise<void>;

export function RemoveStarredRepo(arg1:string):Promise<void>;

export function RenameCategory(arg1:string,arg2:string):Promise<void>;

export function RenamePromptCategory(arg1:string,arg2:string):Promise<void>;

export function ResolveGitConflict(arg1:boolean):Promise<void>;

export function RestoreFromCloud():Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function ScanGitHub(arg1:string):Promise<Array<install.SkillCandidate>>;

export function ScanToolSkills(arg1:string):Promise<Array<main.ToolSkillCandidate>>;

export function SetSkippedUpdateVersion(arg1:string):Promise<void>;

export function UpdateAllStarredRepos():Promise<void>;

export function UpdatePrompt(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<prompt.Prompt>;

export function UpdateSkill(arg1:string):Promise<void>;

export function UpdateStarredRepo(arg1:string):Promise<void>;
