// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomTool(arg1, arg2) {
  return window['go']['main']['App']['AddCustomTool'](arg1, arg2);
}

export function AddStarredRepo(arg1) {
  return window['go']['main']['App']['AddStarredRepo'](arg1);
}

export function AddStarredRepoWithCredentials(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddStarredRepoWithCredentials'](arg1, arg2, arg3);
}

export function ApplyAppUpdate() {
  return window['go']['main']['App']['ApplyAppUpdate']();
}

export function BackupNow() {
  return window['go']['main']['App']['BackupNow']();
}

export function CheckAppUpdate() {
  return window['go']['main']['App']['CheckAppUpdate']();
}

export function CheckAppUpdateAndNotify() {
  return window['go']['main']['App']['CheckAppUpdateAndNotify']();
}

export function CheckMissingPushDirs(arg1) {
  return window['go']['main']['App']['CheckMissingPushDirs'](arg1);
}

export function CheckUpdates() {
  return window['go']['main']['App']['CheckUpdates']();
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreatePrompt(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePrompt'](arg1, arg2, arg3, arg4);
}

export function CreatePromptCategory(arg1) {
  return window['go']['main']['App']['CreatePromptCategory'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function DeletePromptCategory(arg1) {
  return window['go']['main']['App']['DeletePromptCategory'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DeleteSkills(arg1) {
  return window['go']['main']['App']['DeleteSkills'](arg1);
}

export function DeleteToolSkill(arg1, arg2) {
  return window['go']['main']['App']['DeleteToolSkill'](arg1, arg2);
}

export function DownloadAppUpdate(arg1) {
  return window['go']['main']['App']['DownloadAppUpdate'](arg1);
}

export function ExportPrompts() {
  return window['go']['main']['App']['ExportPrompts']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEnabledTools() {
  return window['go']['main']['App']['GetEnabledTools']();
}

export function GetGitConflictPending() {
  return window['go']['main']['App']['GetGitConflictPending']();
}

export function GetLastBackupChanges() {
  return window['go']['main']['App']['GetLastBackupChanges']();
}

export function GetLastBackupCompletedAt() {
  return window['go']['main']['App']['GetLastBackupCompletedAt']();
}

export function GetLogDir() {
  return window['go']['main']['App']['GetLogDir']();
}

export function GetSkillMeta(arg1) {
  return window['go']['main']['App']['GetSkillMeta'](arg1);
}

export function GetSkillMetaByPath(arg1) {
  return window['go']['main']['App']['GetSkillMetaByPath'](arg1);
}

export function GetSkippedUpdateVersion() {
  return window['go']['main']['App']['GetSkippedUpdateVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportLocal(arg1, arg2) {
  return window['go']['main']['App']['ImportLocal'](arg1, arg2);
}

export function ImportPrompts() {
  return window['go']['main']['App']['ImportPrompts']();
}

export function ImportStarSkills(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportStarSkills'](arg1, arg2, arg3);
}

export function InstallFromGitHub(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallFromGitHub'](arg1, arg2, arg3);
}

export function ListAllStarSkills() {
  return window['go']['main']['App']['ListAllStarSkills']();
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListCloudFiles() {
  return window['go']['main']['App']['ListCloudFiles']();
}

export function ListCloudProviders() {
  return window['go']['main']['App']['ListCloudProviders']();
}

export function ListPromptCategories() {
  return window['go']['main']['App']['ListPromptCategories']();
}

export function ListPrompts() {
  return window['go']['main']['App']['ListPrompts']();
}

export function ListRepoStarSkills(arg1) {
  return window['go']['main']['App']['ListRepoStarSkills'](arg1);
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function ListStarredRepos() {
  return window['go']['main']['App']['ListStarredRepos']();
}

export function ListToolSkills(arg1) {
  return window['go']['main']['App']['ListToolSkills'](arg1);
}

export function MovePromptCategory(arg1, arg2) {
  return window['go']['main']['App']['MovePromptCategory'](arg1, arg2);
}

export function MoveSkillCategory(arg1, arg2) {
  return window['go']['main']['App']['MoveSkillCategory'](arg1, arg2);
}

export function OpenFolderDialog(arg1) {
  return window['go']['main']['App']['OpenFolderDialog'](arg1);
}

export function OpenGitBackupDir() {
  return window['go']['main']['App']['OpenGitBackupDir']();
}

export function OpenLogDir() {
  return window['go']['main']['App']['OpenLogDir']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PromptRootDir() {
  return window['go']['main']['App']['PromptRootDir']();
}

export function PullFromTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['PullFromTool'](arg1, arg2, arg3);
}

export function PullFromToolForce(arg1, arg2, arg3) {
  return window['go']['main']['App']['PullFromToolForce'](arg1, arg2, arg3);
}

export function PushStarSkillsToTools(arg1, arg2) {
  return window['go']['main']['App']['PushStarSkillsToTools'](arg1, arg2);
}

export function PushStarSkillsToToolsForce(arg1, arg2) {
  return window['go']['main']['App']['PushStarSkillsToToolsForce'](arg1, arg2);
}

export function PushToTools(arg1, arg2) {
  return window['go']['main']['App']['PushToTools'](arg1, arg2);
}

export function PushToToolsForce(arg1, arg2) {
  return window['go']['main']['App']['PushToToolsForce'](arg1, arg2);
}

export function ReadSkillFileContent(arg1) {
  return window['go']['main']['App']['ReadSkillFileContent'](arg1);
}

export function RemoveCustomTool(arg1) {
  return window['go']['main']['App']['RemoveCustomTool'](arg1);
}

export function RemoveStarredRepo(arg1) {
  return window['go']['main']['App']['RemoveStarredRepo'](arg1);
}

export function RenameCategory(arg1, arg2) {
  return window['go']['main']['App']['RenameCategory'](arg1, arg2);
}

export function RenamePromptCategory(arg1, arg2) {
  return window['go']['main']['App']['RenamePromptCategory'](arg1, arg2);
}

export function ResolveGitConflict(arg1) {
  return window['go']['main']['App']['ResolveGitConflict'](arg1);
}

export function RestoreFromCloud() {
  return window['go']['main']['App']['RestoreFromCloud']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanGitHub(arg1) {
  return window['go']['main']['App']['ScanGitHub'](arg1);
}

export function ScanToolSkills(arg1) {
  return window['go']['main']['App']['ScanToolSkills'](arg1);
}

export function SetSkippedUpdateVersion(arg1) {
  return window['go']['main']['App']['SetSkippedUpdateVersion'](arg1);
}

export function UpdateAllStarredRepos() {
  return window['go']['main']['App']['UpdateAllStarredRepos']();
}

export function UpdatePrompt(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdatePrompt'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateSkill(arg1) {
  return window['go']['main']['App']['UpdateSkill'](arg1);
}

export function UpdateStarredRepo(arg1) {
  return window['go']['main']['App']['UpdateStarredRepo'](arg1);
}
