// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomAgent(arg1, arg2) {
  return window['go']['main']['App']['AddCustomAgent'](arg1, arg2);
}

export function AddStarredRepo(arg1) {
  return window['go']['main']['App']['AddStarredRepo'](arg1);
}

export function AddStarredRepoWithCredentials(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddStarredRepoWithCredentials'](arg1, arg2, arg3);
}

export function ApplyAppUpdate() {
  return window['go']['main']['App']['ApplyAppUpdate']();
}

export function BackupNow() {
  return window['go']['main']['App']['BackupNow']();
}

export function CancelImportPrompts(arg1) {
  return window['go']['main']['App']['CancelImportPrompts'](arg1);
}

export function CheckAppUpdate() {
  return window['go']['main']['App']['CheckAppUpdate']();
}

export function CheckAppUpdateAndNotify() {
  return window['go']['main']['App']['CheckAppUpdateAndNotify']();
}

export function CheckMissingAgentPushDirs(arg1) {
  return window['go']['main']['App']['CheckMissingAgentPushDirs'](arg1);
}

export function CheckUpdates() {
  return window['go']['main']['App']['CheckUpdates']();
}

export function CompleteImportPrompts(arg1, arg2) {
  return window['go']['main']['App']['CompleteImportPrompts'](arg1, arg2);
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreatePrompt(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreatePrompt'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreatePromptCategory(arg1) {
  return window['go']['main']['App']['CreatePromptCategory'](arg1);
}

export function DeleteAgentSkill(arg1, arg2) {
  return window['go']['main']['App']['DeleteAgentSkill'](arg1, arg2);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function DeletePromptCategory(arg1) {
  return window['go']['main']['App']['DeletePromptCategory'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DeleteSkills(arg1) {
  return window['go']['main']['App']['DeleteSkills'](arg1);
}

export function DownloadAppUpdate(arg1) {
  return window['go']['main']['App']['DownloadAppUpdate'](arg1);
}

export function ExportPrompts() {
  return window['go']['main']['App']['ExportPrompts']();
}

export function ExportPromptsByNames(arg1) {
  return window['go']['main']['App']['ExportPromptsByNames'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEnabledAgents() {
  return window['go']['main']['App']['GetEnabledAgents']();
}

export function GetGitConflictPending() {
  return window['go']['main']['App']['GetGitConflictPending']();
}

export function GetLastBackupChanges() {
  return window['go']['main']['App']['GetLastBackupChanges']();
}

export function GetLastBackupCompletedAt() {
  return window['go']['main']['App']['GetLastBackupCompletedAt']();
}

export function GetLogDir() {
  return window['go']['main']['App']['GetLogDir']();
}

export function GetSkillMeta(arg1) {
  return window['go']['main']['App']['GetSkillMeta'](arg1);
}

export function GetSkillMetaByPath(arg1) {
  return window['go']['main']['App']['GetSkillMetaByPath'](arg1);
}

export function GetSkippedUpdateVersion() {
  return window['go']['main']['App']['GetSkippedUpdateVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportLocal(arg1, arg2) {
  return window['go']['main']['App']['ImportLocal'](arg1, arg2);
}

export function ImportPrompts() {
  return window['go']['main']['App']['ImportPrompts']();
}

export function ImportStarSkills(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportStarSkills'](arg1, arg2, arg3);
}

export function ListAgentSkills(arg1) {
  return window['go']['main']['App']['ListAgentSkills'](arg1);
}

export function ListAllStarSkills() {
  return window['go']['main']['App']['ListAllStarSkills']();
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListCloudFiles() {
  return window['go']['main']['App']['ListCloudFiles']();
}

export function ListCloudProviders() {
  return window['go']['main']['App']['ListCloudProviders']();
}

export function ListPromptCategories() {
  return window['go']['main']['App']['ListPromptCategories']();
}

export function ListPrompts() {
  return window['go']['main']['App']['ListPrompts']();
}

export function ListRepoStarSkills(arg1) {
  return window['go']['main']['App']['ListRepoStarSkills'](arg1);
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function ListStarredRepos() {
  return window['go']['main']['App']['ListStarredRepos']();
}

export function MovePromptCategory(arg1, arg2) {
  return window['go']['main']['App']['MovePromptCategory'](arg1, arg2);
}

export function MoveSkillCategory(arg1, arg2) {
  return window['go']['main']['App']['MoveSkillCategory'](arg1, arg2);
}

export function OpenFolderDialog(arg1) {
  return window['go']['main']['App']['OpenFolderDialog'](arg1);
}

export function OpenGitBackupDir() {
  return window['go']['main']['App']['OpenGitBackupDir']();
}

export function OpenLogDir() {
  return window['go']['main']['App']['OpenLogDir']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PrepareImportPrompts() {
  return window['go']['main']['App']['PrepareImportPrompts']();
}

export function PromptRootDir() {
  return window['go']['main']['App']['PromptRootDir']();
}

export function PullFromAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['PullFromAgent'](arg1, arg2, arg3);
}

export function PullFromAgentForce(arg1, arg2, arg3) {
  return window['go']['main']['App']['PullFromAgentForce'](arg1, arg2, arg3);
}

export function PushStarSkillsToAgents(arg1, arg2) {
  return window['go']['main']['App']['PushStarSkillsToAgents'](arg1, arg2);
}

export function PushStarSkillsToAgentsForce(arg1, arg2) {
  return window['go']['main']['App']['PushStarSkillsToAgentsForce'](arg1, arg2);
}

export function PushToAgents(arg1, arg2) {
  return window['go']['main']['App']['PushToAgents'](arg1, arg2);
}

export function PushToAgentsForce(arg1, arg2) {
  return window['go']['main']['App']['PushToAgentsForce'](arg1, arg2);
}

export function ReadSkillFileContent(arg1) {
  return window['go']['main']['App']['ReadSkillFileContent'](arg1);
}

export function RemoveCustomAgent(arg1) {
  return window['go']['main']['App']['RemoveCustomAgent'](arg1);
}

export function RemoveStarredRepo(arg1) {
  return window['go']['main']['App']['RemoveStarredRepo'](arg1);
}

export function RenameCategory(arg1, arg2) {
  return window['go']['main']['App']['RenameCategory'](arg1, arg2);
}

export function RenamePromptCategory(arg1, arg2) {
  return window['go']['main']['App']['RenamePromptCategory'](arg1, arg2);
}

export function ResolveGitConflict(arg1) {
  return window['go']['main']['App']['ResolveGitConflict'](arg1);
}

export function RestoreFromCloud() {
  return window['go']['main']['App']['RestoreFromCloud']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanAgentSkills(arg1) {
  return window['go']['main']['App']['ScanAgentSkills'](arg1);
}

export function SetSkippedUpdateVersion(arg1) {
  return window['go']['main']['App']['SetSkippedUpdateVersion'](arg1);
}

export function TestProxyConnection(arg1, arg2) {
  return window['go']['main']['App']['TestProxyConnection'](arg1, arg2);
}

export function UpdateAllStarredRepos() {
  return window['go']['main']['App']['UpdateAllStarredRepos']();
}

export function UpdatePrompt(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdatePrompt'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateSkill(arg1) {
  return window['go']['main']['App']['UpdateSkill'](arg1);
}

export function UpdateStarredRepo(arg1) {
  return window['go']['main']['App']['UpdateStarredRepo'](arg1);
}
